let express=require('express')
const { addadmin ,adminlogin, islogin, isadmin} = require('../controller/admincont')
const{addemp,emplogin, getdept, getemp, resetpwd}=require('../controller/empcont')
const { addtask, assigntask, accept, gettasks, complet, reject, deltask, getall } = require('../controller/taskcont')
let route=new express.Router()
route.post("/addadmin",addadmin)
route.post("/adminlogin",adminlogin)
route.post("/addemp",addemp)
route.post("/emplogin",emplogin)
route.post("/addtask",islogin,isadmin,addtask)
route.get("/assign/:taskid/:eid",islogin,isadmin,assigntask)
route.get("/accept/:taskid",islogin,accept)
route.get("/gettasks/:eid",islogin,gettasks)
route.get("/complet/:taskid",islogin,complet)
route.get("/reject/:taskid",islogin,reject)
route.delete("/deltask/:taskid",islogin,isadmin,deltask)
route.get("/tasks",islogin,isadmin,getall)
route.get("/getdept",getdept)
route.get("/getemp/:dept",getemp)
route.post("/resetpwd",islogin,resetpwd)

module.exports=route